Made a check in 014-get-scores a la "On Rails"
014-get-scores gets called right after a big computational run
which would most likely involve external parallelization / cluster step
with GNU parallel, a Torque cluster (qsub), or a SLURM cluster.

diff --git a/014-get-scores b/014-get-scores
--- a/014-get-scores
+++ b/014-get-scores
@@ -6,10 +6,17 @@ set -u
 DATA_OUT="$0-data-out"
 mkdir -p $DATA_OUT-new 2> /dev/null && true
 
+SCORE_FILES=`echo \
+  010-run-guidance-data-out/sample*-list-nogaps/*/MSA.MAFFT.Guidance_msa.scr`
 
-grep "MEAN_RES_PAIR_SCORE" \
-  010-run-guidance-data-out/sample*-list-nogaps/*/MSA.MAFFT.Guidance_msa.scr |
-  while read line; do
+# If these files exists then *'s will expand
+if [[ $SCORE_FILES =~ \* ]]; then
+  echo "$0: ERROR: Could not find score files $SCORE_FILES" >&2
+  echo "Did you run the tasks generated by 010-run-guidance?" >&2
+  exit 1
+fi
+
+grep "MEAN_RES_PAIR_SCORE" $SCORE_FILES | while read line; do
 
     sample=`echo $line |
      awk -F"/" '{print $2}' | # Parse directory structure
@@ -35,3 +42,6 @@ rm -rf $DATA_OUT
 
 # Done
 mv $DATA_OUT{-new,}
+
+
+wc -l 014-get-scores-data-out/*
