024-box-plot ready
Results: http://biocluster.ucr.edu/~alevchuk/projects/032-ms/trial-cdd-2011-08-v2.31-uniprot-2011-08/024-box-plot-out/change-figures.html

These are 2500 GUIDANCE scores.

diff --git a/014-get-scores b/014-get-scores
--- a/014-get-scores
+++ b/014-get-scores
@@ -56,14 +56,14 @@ fi
 
 grep "MEAN_RES_PAIR_SCORE" $SCORE_FILES | while read line; do
 
-  sample=$(expr "$line" : '.*\(sample-.*-nogaps\)/[^/]*/.*') || (
-    echo "ERROR: Could not parse \"$line\""; exit 1) || exit 1
+  sample=$(expr "$line" : '.*\(sample-[^/]*-nogaps\)/[^/]*/.*') || (
+    echo "ERROR: Could not parse out sample in \"$line\""; exit 1)
 
   msa=$(expr "$line" : '.*sample-.*-nogaps/\([^/]*\)/.*') || (
-    echo "ERROR: Could not parse \"$line\""; exit 1) || exit 1
+    echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
 
   score=$(expr "$line" : '.*MEAN_COL_SCORE \([^ ]*\).*') || (
-    echo "ERROR: Could not parse \"$line\""; exit 1) || exit 1
+    echo "ERROR: Could not parse out score in \"$line\""; exit 1)
 
   echo -e "$score\t$msa" >> $DATA_OUT-new/$sample-mafft-guidance-msa-scr
 
