Guidance: MEAN_{COL,RES_PAIR}_SCORE = {log,linear}
Going from MEAN_COL_SCORE to MEAN_RES_PAIR_SCORE allowed changing
the trends viewing from log scale to linear scale.

Log scale MEAN_COL_SCORE looks almost exactly like
linear scale MEAN_RES_PAIR_SCORE

Both curves (at their respective scales) look similar
it's a downward trend almost a straight line but slope flattens out
for higher [Amount of foreign residues] values

diff --git a/014-get-scores b/014-get-scores
--- a/014-get-scores
+++ b/014-get-scores
@@ -62,7 +62,9 @@ grep "MEAN_RES_PAIR_SCORE" $SCORE_FILES | while read line; do
   msa=$(expr "$line" : '.*sample-.*-nogaps/\([^/]*\)/.*') || (
     echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
 
-  score=$(expr "$line" : '.*MEAN_COL_SCORE \([^ ]*\).*') || (
+  #score=$(expr "$line" : '.*MEAN_COL_SCORE \([^ ]*\).*') || (
+  #  echo "ERROR: Could not parse out score in \"$line\""; exit 1)
+  score=$(expr "$line" : '.*MEAN_RES_PAIR_SCORE \([^ ]*\).*') || (
     echo "ERROR: Could not parse out score in \"$line\""; exit 1)
 
   echo -e "$score\t$msa" >> $DATA_OUT-new/$sample-mafft-guidance-msa-scr
