026-run-normd now does re-alignment
no more dependency on GUIDANCE scores

diff --git a/026-run-normd b/026-run-normd
--- a/026-run-normd
+++ b/026-run-normd
@@ -21,29 +21,49 @@ set -u
 
 source ./api/pipeline.sh
 
+if [ $# != 1 ] && [ $# != 2 ]; then
+  echo "Usage: $0 <sample-size>  [-s]" >&2
+  echo "" >&2
+  echo "  <sample-size>        how many alignments should be in 1 sample" >&2
+  echo "" >&2
+  echo "  -f                   force always runing, never skip any steps" >&2
+  exit 1
+fi
+
+# Arguments
+SAMPLE_SIZE=$1                              # sample size (mandatory)
+set +u
+[ "$2" == '-f' ] && export ALWAYS_RUN=true  # skip steps (optional)
+[ -n "$2" ] && [ "$2" != '-f' ] && (echo "Invalid option $3"; exit 1)
+set -u
+
 NORMD_RUN_TEMPLATE="$0-scripts/run.sh.template"
 
 EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
 
-# TODO: Take a Higher Upstream
-UPSTREAM="./$EXPERIMENT_NAME/010-run-guidance-data-out"
+UPSTREAM="./$EXPERIMENT_NAME/008-sample-data-out"
 
-DATA_IN="./$EXPERIMENT_NAME/$0-data-in"
+DATA_IN="./$EXPERIMENT_NAME/$0-data-in/tasks"
 DATA_OUT="./$EXPERIMENT_NAME/$0-data-out"
+RAM_DIR="/dev/shm/$EXPERIMENT_NAME-normd-scr"
 
 
 mkdir -p $DATA_IN $DATA_OUT 2> /dev/null && true
 
-# TODO: Align by yourself
-ls $UPSTREAM/sample-size100-id*-list-tab-rand*-tab-nogaps/*.FASTA.tab/MSA.MAFFT.aln.With_Names | while read msa_fasta; do
-  canonical_name=$(echo "$msa_fasta" | awk -F/ '{print $4 "-" $5}')
+#sample-size100-id5-list-tab/
+#sample-size100-id5-list-tab-rand0.05-tab/
+ls $UPSTREAM/sample-size$SAMPLE_SIZE-id*-list-tab*/*.tab |
+while read msa_tab; do
 
-  out_sh="$DATA_IN/$canonical_name.sh"
+  SAMPLE_AND_MSA_NAME=$(echo "$msa_tab" | awk -F/ '{print $4 "-" $5}')
+
+  out_sh="$DATA_IN/$SAMPLE_AND_MSA_NAME.sh"
   cat $NORMD_RUN_TEMPLATE |
-    sed "s|%%DATA_OUT%%|$DATA_OUT|g" |
+    sed "s|%%DATA_OUT%%|$DATA_OUT/$SAMPLE_AND_MSA_NAME|g" |
     sed "s|%%WD%%|`pwd`|g" |
-    sed "s|%%MSA_FASTA%%|$msa_fasta|g" |
-    sed "s|%%CANONICAL_NAME%%|$canonical_name|g" |
+    sed "s|%%MSA_TAB%%|$msa_tab|g" |
+    sed "s|%%SAMPLE_AND_MSA_NAME%%|$SAMPLE_AND_MSA_NAME|g" |
+    sed "s|%%RAM_DIR%%|$RAM_DIR/$SAMPLE_AND_MSA_NAME|g" |
       cat > $out_sh
     chmod +x $out_sh
 
diff --git a/026-run-normd-scripts/run.sh.template b/026-run-normd-scripts/run.sh.template
--- a/026-run-normd-scripts/run.sh.template
+++ b/026-run-normd-scripts/run.sh.template
@@ -1,50 +1,122 @@
 #!/bin/bash
 
+# UNNAMED is a classifier of outlier sequences in multiple alignments
+# Copyright (C) 2011  Aleksandr Levchuk
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 set -e
 set -u
 
-working_d=%%WD%%
+WORKING_D=%%WD%%
 
 DATA_OUT=%%DATA_OUT%%
 
+MSA_TAB=%%MSA_TAB%%
 
-msa_fasta=%%MSA_FASTA%%
+SAMPLE_AND_MSA_NAME=%%SAMPLE_AND_MSA_NAME%%
 
-canonical_name=%%CANONICAL_NAME%%
+RAM_DIR=%%RAM_DIR%%
 
 
+OPT_DIR="$WORKING_D/opt"
 
-NORMD="./opt/norMD1_3/normd"
-SCORING_MATRIX="./opt/norMD1_3/gon250.bla"
+NORMD="$OPT_DIR/norMD1_3/normd"
+SCORING_MATRIX="$OPT_DIR/norMD1_3/gon250.bla"
 NORMD_OPTS="$SCORING_MATRIX 0 0 0 -v"
+MAFFT_PATH="$OPT_DIR/mafft-6.857-with-extensions/bin"
+CONVERT_FASTA_TO_TAB="$OPT_DIR/misc-bioinfo-scripts/convert-fasta-to-tab"
 
-cd $working_d
+seq_group_tab=$MSA_TAB
+seq_group_fasta=$MSA_TAB-fasta.txt
+cat $seq_group_tab | awk '{print ">" $1 "\n" $2}' > $seq_group_fasta
 
-out_normd_file=$DATA_OUT/$canonical_name-whole-msa-normd-scr
-out_normd_mod_file=$DATA_OUT/$canonical_name-whole-msa-normd-mod-scr
+num_seq=$(wc -l $seq_group_tab| awk '{print $1}')
 
-# Run NorMD 
+mkdir -p $RAM_DIR 2> /dev/null && true
+
+rm -rf $DATA_OUT-new
+mkdir -p $DATA_OUT-new
+
+
+# Align
+msa_fasta=$RAM_DIR/msa-mafft-fasta.txt
+$MAFFT_PATH/mafft  --reorder --amino  --quiet $seq_group_fasta > $msa_fasta
+msa_tab=$msa_fasta-tab.txt
+cat $msa_fasta | $CONVERT_FASTA_TO_TAB > $msa_tab
+
+
+# Get the whole MSA score
 set +e
 score_raw=$($NORMD $msa_fasta $NORMD_OPTS)
 set -e
+(echo "$score_raw" | grep "ERROR") && (echo "$score_raw" >&2 exit 1 )
+whole_normd=$(echo "$score_raw" | egrep "^norMD" | awk '{print $2}')
+whole_lqrid=$(echo "$score_raw" | egrep "^LQR" | awk '{print $2}')
+whole_md=$(echo "$score_raw" | egrep "^MD" | awk '{print $2}')
+whole_maxmd=$(echo "$score_raw" | egrep "^maxMD" | awk '{print $2}')
+WHOLE_NORMD_MOD=$(ruby -e "puts $whole_md / $whole_maxmd")
+echo $WHOLE_NORMD_MOD > $DATA_OUT-new/whole-msa-score
 
-(echo "$score_raw" | grep "ERROR") && (
-  echo "$score_raw" >&2
-  exit 1 )
+# Remove sequences and score
+ram_file1=$RAM_DIR/normd-dx1-mod-seq-scores.txt
+cat /dev/null > $ram_file1
+for seq_id in `seq 1 $num_seq`; do
+  ram_file2=$RAM_DIR/seq$seq_id-removed
+  seq_name=$(cat $msa_tab | awk "NR==$seq_id" | awk '{print $1}')
 
-normd=$(echo "$score_raw" | egrep "^norMD" | awk '{print $2}')
-lqrid=$(echo "$score_raw" | egrep "^LQR" | awk '{print $2}')
-md=$(echo "$score_raw" | egrep "^MD" | awk '{print $2}')
-maxmd=$(echo "$score_raw" | egrep "^maxMD" | awk '{print $2}')
-# By the way: NORMD = MD / (MaxMD * LQRID)
+  # Remove a sequence
+  cat $msa_tab | awk "NR!=$seq_id" > $ram_file2
 
-normd_mod=$(ruby -e "puts $md / $maxmd")
+  # Convert tab to FASTA
+  cat $ram_file2 | awk '{print ">" $1 "\n" $2}' > $ram_file2-fasta
 
-echo -e "$normd" > $out_normd_file
-sort -k2 $out_normd_file > $out_normd_file-srt
-mv $out_normd_file-srt $out_normd_file        
+  # Re-Align
+  $MAFFT_PATH/mafft  --reorder --amino  --quiet $ram_file2-fasta > \
+    $ram_file2-fasta-mafft
 
+  # Run NorMD 
+  set +e
+  score_raw=$($NORMD $ram_file2-fasta-mafft $NORMD_OPTS)
+  set -e
+  (echo "$score_raw" | grep "ERROR") && (echo "$score_raw" >&2 exit 1)
 
-echo -e "$normd_mod" > $out_normd_mod_file
-sort -k2 $out_normd_mod_file > $out_normd_mod_file-srt
-mv $out_normd_mod_file-srt $out_normd_mod_file        
+  normd=$(echo "$score_raw" | egrep "^norMD" | awk '{print $2}')
+  lqrid=$(echo "$score_raw" | egrep "^LQR" | awk '{print $2}')
+  md=$(echo "$score_raw" | egrep "^MD" | awk '{print $2}')
+  maxmd=$(echo "$score_raw" | egrep "^maxMD" | awk '{print $2}')
+  # By the way: NORMD = MD / (MaxMD * LQRID)
+
+  normd_dx1_mod=$(ruby -e "puts $WHOLE_NORMD_MOD - ($md / $maxmd)")
+
+  # Output
+  echo -e "$seq_name\t$normd_dx1_mod" >> $ram_file1
+
+  rm $ram_file2
+done
+
+# Can't use sort -n because the file is in scientific notation
+cat $ram_file1 | ruby -e 'STDIN.readlines.collect{|x|
+  v1,v2=x.split
+  [v1, v2.to_f]}.sort{|i1,i2|
+  i1[1] <=> i2[1]}.each{|x| puts "#{x[0]}\t#{x[1]}"}' > $ram_file1-srt
+
+mv $ram_file1-srt   $DATA_OUT-new/per-seq-scores-normd-dx1-mod
+
+rm -rf $DATA_OUT
+mv $DATA_OUT{-new,}
+
+rm -rf $RAM_DIR 2> /dev/null && true
+
+exit 0
