077-plot-density automated for both methods

diff --git a/028-get-normd-scores b/028-get-normd-scores
--- a/028-get-normd-scores
+++ b/028-get-normd-scores
@@ -30,9 +30,8 @@ if [ $# != 1 ] && [ $# != 2 ]; then
 fi
 
 # Arguments
-w
 SAMPLE_SIZE=$1                              # sample size (mandatory)
-set +u
+set +u
 [ "$2" == '-f' ] && export ALWAYS_RUN=true  # skip steps (optional)
 [ -n "$2" ] && [ "$2" != '-f' ] && (echo "Invalid option $3"; exit 1)
 set -u
@@ -42,30 +41,44 @@ EXPERIMENT_NAME=$(ls -1d ./trial-*/ | tail -1 | cut -d/ -f 2)
 UPSTREAM_DIR="./$EXPERIMENT_NAME/027-run-normd-with-removals-data-out"
 
 DATA_OUT="$EXPERIMENT_NAME/$0-data-out/sample-size$SAMPLE_SIZE"
+
+rm -rf $DATA_OUT-new # Danger Zone
 mkdir -p $DATA_OUT-new 2> /dev/null && true
 
-cat $UPSTREAM_DIR/normd-scores | while read line; do
 
-  sample=$(expr "$line" : '.*\(sample-[^/]*-nogaps\)/[^/]*/.*') || (
+#
+# Per sequence scores
+#
+
+MSA_SCORE_FILES=`echo \
+  $UPSTREAM_DIR/sample-size$SAMPLE_SIZE-id1-list-tab-*normd-dx1-mod-seq-scr |
+  tr " " "\n"`
+
+# If these files exists then *'s will expand
+if [[ $MSA_SCORE_FILES =~ \* ]]; then
+  echo "$0: ERROR: Could not find score files $MSA_SCORE_FILES" >&2
+  echo "Did you run the tasks generated by 010-run-guidance?" >&2
+  exit 1
+fi
+
+echo -e "$MSA_SCORE_FILES" | while read line; do
+  sample=$(expr "$line" : '.*\(sample-size[0-9]*-.*\)-nogaps') || (
     echo "ERROR: Could not parse out sample in \"$line\""; exit 1)
 
-  msa=$(expr "$line" : '.*sample-.*-nogaps/\([^/]*\)/.*') || (
+  msa=$(expr "$line" : '.*sample-size[0-9]*-id.*-nogaps-\([^-]*\)-') || (
     echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
 
-  #score=$(expr "$line" : '.*MEAN_COL_SCORE \([^ ]*\).*') || (
-  #  echo "ERROR: Could not parse out score in \"$line\""; exit 1)
-  #score=$(expr "$line" : '.*MEAN_RES_PAIR_SCORE \([^ ]*\).*') || (
-  #  echo "ERROR: Could not parse out score in \"$line\""; exit 1)
-  score=$(echo $line | awk '{print $2}')
+  rand=$(expr "$line" : '.*sample-size[0-9]*-id.*-nogaps-\([^-]*\)-') || (
+    echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
 
-  echo -e "$score\t$msa" >> $DATA_OUT-new/$sample-normd-msa-scr
-
+  cat $line | while read line_of_file; do 
+    score=$(echo $line_of_file | awk '{print $2}')
+    seq=$(echo $line_of_file | awk '{print $1}')
+    echo -e "$score\t$seq\t$msa" >> \
+      $DATA_OUT-new/$sample-normd-dx-mod-scr
+  done
 done
 
-for i in $DATA_OUT-new/*-normd-msa-scr; do
-  sort -nk 2 $i > $i-new
-  mv $i{-new,}
-done
 
 
 # Danger Zone
