collect-scores reuse open files improved 3h to 30s
I did not yet optimize the whole score collection.
The unoptimized version takes 3m.
for now the whole score collection will not be performed.

Also dropped sorting as it is not necessary.
Sorting takes about 1s.

diff --git a/029-collect-scores b/029-collect-scores
--- a/029-collect-scores
+++ b/029-collect-scores
@@ -52,86 +52,86 @@ mkdir -p $DATA_OUT-new 2> /dev/null && true
 
 
 function callback {
+  ##
+  ## GUIDANCE Whole MSA scores
+  ##
+  #sample_portion="sample-size$SAMPLE_SIZE*-nogaps"
+  #MSA_SCORE_FILES=`echo \
+  #  $GUIDANCE_UPSTREAM_DIR/$sample_portion/*/MSA.MAFFT.Guidance_msa.scr |
+  #  tr " " "\n"`
   #
-  # GUIDANCE Whole MSA scores
+  ## If these files exists then *'s will expand
+  #if [[ $MSA_SCORE_FILES =~ \* ]]; then
+  #  echo "$0: ERROR: Could not find score files $MSA_SCORE_FILES" >&2
+  #  echo "Did you run the tasks generated by 010-run-guidance?" >&2
+  #  exit 1
+  #fi
   #
-  sample_portion="sample-size$SAMPLE_SIZE*-nogaps"
-  MSA_SCORE_FILES=`echo \
-    $GUIDANCE_UPSTREAM_DIR/$sample_portion/*/MSA.MAFFT.Guidance_msa.scr |
-    tr " " "\n"`
-  
-  # If these files exists then *'s will expand
-  if [[ $MSA_SCORE_FILES =~ \* ]]; then
-    echo "$0: ERROR: Could not find score files $MSA_SCORE_FILES" >&2
-    echo "Did you run the tasks generated by 010-run-guidance?" >&2
-    exit 1
-  fi
-  
-  grep "MEAN_RES_PAIR_SCORE" $MSA_SCORE_FILES | while read line; do
+  #grep "MEAN_RES_PAIR_SCORE" $MSA_SCORE_FILES | while read line; do
 
-    #./trial-cdd-2011-08-v2.31-uniprot-2011-08/
-    #010-run-guidance-data-out/sample-size100-id1-list-tab-nogaps/
-    # [           sample-size100-id3-list-tab-rand0.05-tab-nogaps  ]
-    #COG0081.FASTA.tab-fasta.txt/
-    #MSA.MAFFT.Guidance_msa.scr:#MEAN_RES_PAIR_SCORE
-    #0.892144  #MEAN_COL_SCORE 0.330662
+  #  #./trial-cdd-2011-08-v2.31-uniprot-2011-08/
+  #  #010-run-guidance-data-out/sample-size100-id1-list-tab-nogaps/
+  #  # [           sample-size100-id3-list-tab-rand0.05-tab-nogaps  ]
+  #  #COG0081.FASTA.tab-fasta.txt/
+  #  #MSA.MAFFT.Guidance_msa.scr:#MEAN_RES_PAIR_SCORE
+  #  #0.892144  #MEAN_COL_SCORE 0.330662
  
-    sample=$(expr "$line" : '.*\(sample-size.*-id.*\)-list') || (
-      echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  sample=$(expr "$line" : '.*\(sample-size.*-id.*\)-list') || (
+  #    echo "error: could not parse out rand in \"$line\""; exit 1)
 
-    rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab-nogaps') || (
-      echo "error: could not parse out rand in \"$line\""; exit 1)
-    if [ "$rand" == "t" ]; then
-      rand="0.00"
-    else
-      rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
-        echo "error: could not parse out rand in \"$line\""; exit 1)
-    fi
+  #  rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab-nogaps') || (
+  #    echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  if [ "$rand" == "t" ]; then
+  #    rand="0.00"
+  #  else
+  #    rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
+  #      echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  fi
 
-    msa=$(expr "$line" : '.*sample-.*-nogaps/\(.*\).FASTA.tab') || (
-      echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
-  
-    score=$(expr "$line" : '.*MEAN_RES_PAIR_SCORE \([^ ]*\).*') || (
-      echo "ERROR: Could not parse out score in \"$line\""; exit 1)
- 
-    # SCORE RAND_AMMOUNT UNUSED MSA METHOD
-    echo -e "$score\t$rand\t-\t$msa\tguidance_mean_res_pair_msa" \
-      >> $DATA_OUT-new/$sample-whole-msa-scores
-  
-  done
- 
- 
+  #  msa=$(expr "$line" : '.*sample-.*-nogaps/\(.*\).FASTA.tab') || (
+  #    echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
   #
-  # NorMD whole MSA scores
+  #  score=$(expr "$line" : '.*MEAN_RES_PAIR_SCORE \([^ ]*\).*') || (
+  #    echo "ERROR: Could not parse out score in \"$line\""; exit 1)
+ 
+  #  # SCORE RAND_AMMOUNT UNUSED MSA METHOD
+  #  echo -e "$score\t$rand\t-\t$msa\tguidance_mean_res_pair_msa" \
+  #    >> $DATA_OUT-new/$sample-whole-msa-scores
   #
-  find $NORMD_UPSTREAM_DIR | grep "whole-msa-score$" |
-  while read line; do
-    # trial-cdd-2011-08-v2.31-uniprot-2011-08/026-run-normd-data-out/
-    # sample-size100-id5-list-tab-rand0.50-tab-pfam04267.FASTA.tab/
-    # whole-msa-score 
+  #done
+ 
+ 
+  ##
+  ## NorMD whole MSA scores
+  ##
+  #find $NORMD_UPSTREAM_DIR | grep "whole-msa-score$" |
+  #while read line; do
+  #  # trial-cdd-2011-08-v2.31-uniprot-2011-08/026-run-normd-data-out/
+  #  # sample-size100-id5-list-tab-rand0.50-tab-pfam04267.FASTA.tab/
+  #  # whole-msa-score 
 
-    sample=$(expr "$line" : '.*\(sample-size[0-9]*-.*\)-list-tab') || (
-      echo "ERROR: Could not parse out sample in \"$line\""; exit 1)
+  #  sample=$(expr "$line" : '.*\(sample-size[0-9]*-.*\)-list-tab') || (
+  #    echo "ERROR: Could not parse out sample in \"$line\""; exit 1)
 
-    rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab') || (
-      echo "error: could not parse out rand in \"$line\""; exit 1)
-    if [ "$rand" == "t" ]; then
-      rand="0.00"
-    else
-      rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
-        echo "error: could not parse out rand in \"$line\""; exit 1)
-    fi
+  #  rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab') || (
+  #    echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  if [ "$rand" == "t" ]; then
+  #    rand="0.00"
+  #  else
+  #    rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
+  #      echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  fi
 
-    msa=$(expr "$line" : '.*-tab-\([^.]*\).FASTA.tab') || (
-      echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
+  #  msa=$(expr "$line" : '.*-tab-\([^.]*\).FASTA.tab') || (
+  #    echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
 
-    score=$(cat $line)
+  #  score=$(cat $line)
 
-    # SCORE RAND_AMMOUNT UNUSED MSA METHOD
-    echo -e "$score\t$rand\t-\t$msa\tnormd_dx_mod_msa" >> \
-      $DATA_OUT-new/$sample-whole-msa-scores  # Add to the same file as GUID..
+  #  # SCORE RAND_AMMOUNT UNUSED MSA METHOD
+  #  echo -e "$score\t$rand\t-\t$msa\tnormd_dx_mod_msa" >> \
+  #    $DATA_OUT-new/$sample-whole-msa-scores  # Add to the same file as GUID..
 
-  done
+  #done
 
  
   #
@@ -150,85 +150,161 @@ function callback {
     exit 1
   fi
   
-  egrep -v "^#END$" $SEQ_SCORE_FILES | grep -v SEQUENCE_NAME | \
-  while read line; do
-  
-    #./trial-cdd-2011-08-v2.31-uniprot-2011-08/010-run-guidance-data-out/
-    #sample-size100-id1-list-tab-nogaps/COG0081.FASTA.tab-fasta.txt/
-    #MSA.MAFFT.Guidance_res_pair_seq.scr_with_Names:gi|6320321	0.735626
- 
-    sample=$(expr "$line" : '.*\(sample-size.*-id.*\)-list') || (
-      echo "error: could not parse out sample in \"$line\""; exit 1)
-  
-    msa=$(expr "$line" : '.*sample-.*-nogaps/\(.*\).FASTA.tab') || (
-      echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
-  
-    rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab-nogaps') || (
-      echo "error: could not parse out rand in \"$line\""; exit 1)
-    if [ "$rand" == "t" ]; then
-      rand="0.00"
-    else
-      rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
-        echo "error: could not parse out rand in \"$line\""; exit 1)
-    fi
+  #./trial-cdd-2011-08-v2.31-uniprot-2011-08/010-run-guidance-data-out/
+  #sample-size100-id1-list-tab-nogaps/COG0081.FASTA.tab-fasta.txt/
+  #MSA.MAFFT.Guidance_res_pair_seq.scr_with_Names:gi|6320321	0.735626
+  egrep -v "^#END$" $SEQ_SCORE_FILES | grep -v "SEQUENCE_NAME" | \
+  ruby -e '
+    open_out_files = {}
+    while line = STDIN.gets
 
-    payload=$(expr "$line" : '.*_seq.scr_with_Names:\(.*\)$') || (
-      echo "ERROR: Could not parse out payload in \"$line\""; exit 1)
-  
-    # Parse payload 
-    score=$(echo "$payload" | awk '{print $2}' )
-    seq=$(echo "$payload" | awk '{print $1}' )
-  
-    # SCORE RAND_AMMOUNT UNUSED MSA METHOD SEQ 
-    echo -e "$score\t$rand\t-\t$msa\tguidance_seq_scr\t$seq" \
-     >> $DATA_OUT-new/$sample-seq-scores
-  done
+      line =~ /(sample-size.*-id.*)-list/ ?
+        (sample = $1) : (raise "Could not parse sample out of #{line}")
+
+      line =~ /sample-.*\/([^\/]+).FASTA.tab/ ?
+        (msa = $1) : (raise "Could not parse msa out of #{line}")
+
+      if line =~ /sample-size.*-rand([^-]*)-/
+        rand = $1
+      elsif line =~ /sample-size.*-list-tab-nogaps\/#{msa}/
+        rand = "0.00"
+      else
+        raise "Could not parse rand out of #{line}"
+      end
+
+      if line =~ /_seq.scr_with_Names:(.*)\t(.*)/
+        seq,score = $1,$2
+      else
+        raise "Could not parse seq and score out of #{line}"
+      end
+    
+      file_name = "#{ARGV[0]}-new/#{sample}-seq-scores"
+
+      open_out_files[file_name] = File.open(file_name, "w") unless 
+        open_out_files.keys.include? file_name
+
+      open_out_files[file_name].puts \
+        [score,rand,"-",msa,"guidance_seq_scr",seq].join("\t")
+    end
+  ' $DATA_OUT
+
+  #while read line; do
+  #  sample=$(echo "$line" | cut -f1)
+  #  msa=$(echo "$line" | cut -f2)
+  #  rand=$(echo "$line" | cut -f3)
+  #  seq=$(echo "$line" | cut -f4)
+  #  score=$(echo "$line" | cut -f5)
+
+  #  # SCORE RAND_AMMOUNT UNUSED MSA METHOD SEQ 
+  #  echo -e "$score\t$rand\t-\t$msa\tguidance_seq_scr\t$seq" \
+  #   >> $DATA_OUT-new/$sample-seq-scores
+  #
+
+  #  #sample=$(expr "$line" : '.*\(sample-size.*-id.*\)-list') || (
+  #  #  echo "error: could not parse out sample in \"$line\""; exit 1)
+  #
+  #  #msa=$(expr "$line" : '.*sample-.*-nogaps/\(.*\).FASTA.tab') || (
+  #  #  echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
+  #
+  #  #rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab-nogaps') || (
+  #  #  echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  #if [ "$rand" == "t" ]; then
+  #  #  rand="0.00"
+  #  #else
+  #  #  rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
+  #  #    echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  #fi
+
+  #  #payload=$(expr "$line" : '.*_seq.scr_with_Names:\(.*\)$') || (
+  #  #  echo "ERROR: Could not parse out payload in \"$line\""; exit 1)
+  #
+  #  ## Parse payload 
+  #  #score=$(echo "$payload" | awk '{print $2}' )
+  #  #seq=$(echo "$payload" | awk '{print $1}' )
+  #
+  #done
 
 
   #
   # NorMD Per sequence scores
   #
   find $NORMD_UPSTREAM_DIR | grep "per-seq-scores-normd-dx1-mod$" |
-  while read line; do
-    # trial-cdd-2011-08-v2.31-uniprot-2011-08/026-run-normd-data-out/
-    # sample-size100-id5-list-tab-rand0.50-tab-pfam04267.FASTA.tab/
-    # per-seq-scores-normd-dx1-mod
+  # trial-cdd-2011-08-v2.31-uniprot-2011-08/026-run-normd-data-out/
+  # sample-size100-id5-list-tab-rand0.50-tab-pfam04267.FASTA.tab/
+  # per-seq-scores-normd-dx1-mod
+  ruby -e '
+    open_out_files = {}
+    while line = STDIN.gets
 
-    sample=$(expr "$line" : '.*\(sample-size[0-9]*-.*\)-list-tab') || (
-      echo "ERROR: Could not parse out sample in \"$line\""; exit 1)
+      line =~ /(sample-size.*-id.*)-list/ ?
+        (sample = $1) : (raise "Could not parse sample out of #{line}")
 
-    rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab') || (
-      echo "error: could not parse out rand in \"$line\""; exit 1)
-    if [ "$rand" == "t" ]; then
-      rand="0.00"
-    else
-      rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
-        echo "error: could not parse out rand in \"$line\""; exit 1)
-    fi
+      line =~ /sample-.*tab-([^-]+).FASTA.tab/ ?
+        (msa = $1) : (raise "Could not parse msa out of #{line}")
 
-    msa=$(expr "$line" : '.*-tab-\([^.]*\).FASTA.tab') || (
-      echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
+      if line =~ /sample-size.*-rand([^-]*)-/
+        rand = $1
+      elsif line =~ /sample-size.*-list-tab-#{msa}/
+        rand = "0.00"
+      else
+        raise "Could not parse rand out of #{line}"
+      end
 
-    cat $line | while read score_line; do
-      seq=$(echo "$score_line" | awk '{print $1}')
-      score=$(echo "$score_line" | awk '{print $2}')
+      out_file_name = "#{ARGV[0]}-new/#{sample}-seq-scores"
 
-      # SCORE RAND_AMMOUNT UNUSED MSA METHOD SEQ
-      echo -e "$score\t$rand\t-\t$msa\tnormd_dx_mod_seq_scr\t$seq" >> \
-        $DATA_OUT-new/$sample-seq-scores # Add to the same file as GUID..
-    done
+      # Append because GUIDANCE scores are already there
+      open_out_files[out_file_name] = File.open(out_file_name, "a") unless 
+        open_out_files.keys.include? out_file_name
 
-  done
+      in_file_name = line.chomp
+      File.open(in_file_name) do |f|
+        f.each do |line|
+          seq, score = line.chomp.split("\t")
+
+          open_out_files[out_file_name].puts \
+            [score,rand,"-",msa,"normd_dx_mod_seq_scr",seq].join("\t")
+        end
+      end
+    end
+  ' $DATA_OUT
+
+  #while read line; do
+  #  sample=$(echo "$line" | cut -f1)
+  #  msa=$(echo "$line" | cut -f2)
+  #  rand=$(echo "$line" | cut -f3)
+  #  filename=$(echo "$line" | cut -f4)
+
+  #  cat $filename | while read score_line; do
+  #    seq=$(echo "$score_line" | awk '{print $1}')
+  #    score=$(echo "$score_line" | awk '{print $2}')
+
+  #    # SCORE RAND_AMMOUNT UNUSED MSA METHOD SEQ
+  #    echo -e "$score\t$rand\t-\t$msa\tnormd_dx_mod_seq_scr\t$seq" >> \
+  #      $DATA_OUT-new/$sample-seq-scores # Add to the same file as GUID..
+  #  done
+
+  #  #sample=$(expr "$line" : '.*\(sample-size[0-9]*-.*\)-list-tab') || (
+  #  #  echo "ERROR: Could not parse out sample in \"$line\""; exit 1)
+
+  #  #rand=$(expr "$line" : '.*sample-size.*-id.*-lis\(.*\)-tab') || (
+  #  #  echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  #if [ "$rand" == "t" ]; then
+  #  #  rand="0.00"
+  #  #else
+  #  #  rand=$(expr "$rand" : 't-tab-rand\(.*\)') || (
+  #  #    echo "error: could not parse out rand in \"$line\""; exit 1)
+  #  #fi
+
+  #  #msa=$(expr "$line" : '.*-tab-\([^.]*\).FASTA.tab') || (
+  #  #  echo "ERROR: Could not parse out msa in \"$line\""; exit 1)
+
+
+  #done
 
    
   #
   # Finalize
   #
-  # Sort all files by columns 4 then 3, 2, 1 - MSA name, unused, rand, score
-  for i in $DATA_OUT-new/*-scores; do
-    sort -k4,3 $i > $i-new
-    mv $i{-new,}
-  done
   
   # Danger Zone
   rm -rf $DATA_OUT
